name: bratara_puls
description: O aplicație Flutter care citește pulsul de la un ESP32 prin BLE.

publish_to: 'none' # nu se publică pe pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.12
  permission_handler: ^11.3.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.4
  intl: ^0.20.2
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
