// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9OwViser-pHVes_TXZJaLjZprsCkDIc',
    appId: '1:637307250452:web:29288f94e67f886751c401',
    messagingSenderId: '637307250452',
    projectId: 'bratarapuls',
    authDomain: 'bratarapuls.firebaseapp.com',
    storageBucket: 'bratarapuls.firebasestorage.app',
    measurementId: 'G-8TD659XWRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9NR2q2h5Ox5fckbuPraOLtZfCZZqmhZc',
    appId: '1:637307250452:android:8b1fbbcef864198e51c401',
    messagingSenderId: '637307250452',
    projectId: 'bratarapuls',
    storageBucket: 'bratarapuls.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAytPY-Q_vXkyOLF160-1upYJsJfw2hWwk',
    appId: '1:637307250452:ios:b5108612e75551ed51c401',
    messagingSenderId: '637307250452',
    projectId: 'bratarapuls',
    storageBucket: 'bratarapuls.firebasestorage.app',
    iosClientId: '637307250452-7qcoobrgmf27f3oqquk2njc08m3pbp91.apps.googleusercontent.com',
    iosBundleId: 'com.example.brataraPulsNou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAytPY-Q_vXkyOLF160-1upYJsJfw2hWwk',
    appId: '1:637307250452:ios:b5108612e75551ed51c401',
    messagingSenderId: '637307250452',
    projectId: 'bratarapuls',
    storageBucket: 'bratarapuls.firebasestorage.app',
    iosClientId: '637307250452-7qcoobrgmf27f3oqquk2njc08m3pbp91.apps.googleusercontent.com',
    iosBundleId: 'com.example.brataraPulsNou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9OwViser-pHVes_TXZJaLjZprsCkDIc',
    appId: '1:637307250452:web:c0d86baaca21b2f651c401',
    messagingSenderId: '637307250452',
    projectId: 'bratarapuls',
    authDomain: 'bratarapuls.firebaseapp.com',
    storageBucket: 'bratarapuls.firebasestorage.app',
    measurementId: 'G-TR0190HCNN',
  );
}
